#!/usr/bin/env bash
# =============================================================================
# help.sh — Help system: usage info and per-command documentation
# =============================================================================

# Program version
ZIVPN_MANAGER_VERSION="1.6.1"

# ---------------------------------------------------------------------------
# show_version — Print version
# ---------------------------------------------------------------------------
show_version() {
    echo "zivpn-manager v${ZIVPN_MANAGER_VERSION}"
}

# ---------------------------------------------------------------------------
# show_usage — Quick usage summary (shown on invalid command)
# ---------------------------------------------------------------------------
show_usage() {
    echo ""
    echo -e "${BOLD}ZiVPN Account Manager v${ZIVPN_MANAGER_VERSION}${RESET}"
    echo ""
    echo -e "${BOLD}Penggunaan:${RESET}"
    echo "  zivpn-manager                  Buka menu interaktif (TUI)"
    echo "  zivpn-manager <perintah>       Jalankan perintah langsung"
    echo "  zivpn-manager help             Tampilkan bantuan lengkap"
    echo "  zivpn-manager help <perintah>  Bantuan untuk perintah tertentu"
    echo ""
    echo -e "${BOLD}Perintah yang tersedia:${RESET}"
    echo ""
    echo -e "  ${GREEN}Manajemen Akun:${RESET}"
    echo "    list           Lihat daftar semua akun"
    echo "    add            Tambah akun baru"
    echo "    delete         Hapus akun"
    echo "    trial          Buat akun trial (durasi pendek)"
    echo "    extend         Perpanjang masa aktif akun"
    echo "    set-expired    Set tanggal expired akun"
    echo "    domain         Set atau hapus custom domain"
    echo ""
    echo -e "  ${CYAN}Backup & Restore:${RESET}"
    echo "    backup         Buat backup data (akun, config, sertifikat)"
    echo "    restore        Restore data dari file backup"
    echo "    backups        Lihat daftar file backup"
    echo ""
    echo -e "  ${GRAY}Service & Info:${RESET}"
    echo "    status         Lihat status service ZiVPN"
    echo "    restart        Restart service ZiVPN"
    echo "    info           Lihat info server dan konfigurasi"
    echo ""
    echo -e "  ${GRAY}Lainnya:${RESET}"
    echo "    help           Tampilkan bantuan ini"
    echo "    help <cmd>     Bantuan detail untuk perintah tertentu"
    echo "    update         Cek dan install update dari GitHub"
    echo "    uninstall      Hapus ZiVPN dan semua data dari server"
    echo "    version        Tampilkan versi"
    echo "    expire-check   Cek & nonaktifkan akun expired (untuk cron)"
    echo ""
    echo -e "Contoh: ${CYAN}zivpn-manager add${RESET}"
    echo -e "        ${CYAN}zivpn-manager help backup${RESET}"
    echo ""
}

# ---------------------------------------------------------------------------
# show_help_topic — Detailed help per command
# ---------------------------------------------------------------------------
show_help_topic() {
    local topic="$1"

    case "$topic" in
        list)
            echo ""
            echo -e "${BOLD}zivpn-manager list${RESET}"
            echo ""
            echo -e "${BOLD}Deskripsi:${RESET}"
            echo "  Menampilkan semua akun yang terdaftar dalam format tabel."
            echo "  Informasi yang ditampilkan: username, password, status,"
            echo "  tanggal expired, dan sisa hari masa aktif."
            echo ""
            echo -e "${BOLD}Penggunaan:${RESET}"
            echo "  zivpn-manager list"
            echo ""
            echo -e "${BOLD}Contoh output:${RESET}"
            echo "  No   Username         Password       Status     Expired At             Sisa"
            echo "  1    john             aB3kX9mP2q     aktif      15 Apr 2026 00:00 UTC  38 hari"
            echo "  2    trial_user       xK7pQ2wR       trial      10 Mar 2026 00:00 UTC  2 hari"
            echo "  3    expired_user     mN4vL8tY       expired    01 Mar 2026 00:00 UTC  Expired"
            echo ""
            echo -e "${BOLD}Status akun:${RESET}"
            echo "  aktif     Akun bisa digunakan"
            echo "  trial     Akun percobaan yang masih aktif"
            echo "  expired   Akun sudah melewati masa aktif"
            echo "  nonaktif  Akun dinonaktifkan manual"
            echo ""
            ;;

        add)
            echo ""
            echo -e "${BOLD}zivpn-manager add${RESET}"
            echo ""
            echo -e "${BOLD}Deskripsi:${RESET}"
            echo "  Membuat akun VPN baru. Anda akan diminta memasukkan username,"
            echo "  password (opsional, bisa auto-generate), dan durasi masa aktif."
            echo "  Setelah akun dibuat, informasi koneksi akan ditampilkan untuk"
            echo "  diberikan ke pengguna."
            echo ""
            echo -e "${BOLD}Penggunaan:${RESET}"
            echo "  zivpn-manager add"
            echo ""
            echo -e "${BOLD}Langkah-langkah:${RESET}"
            echo "  1. Masukkan username (3-32 karakter, huruf/angka/underscore/hyphen)"
            echo "  2. Masukkan password atau tekan Enter untuk auto-generate"
            echo "  3. Masukkan durasi dalam hari (default: 30 hari)"
            echo "  4. Konfirmasi untuk menyimpan"
            echo ""
            echo -e "${BOLD}Contoh:${RESET}"
            echo "  \$ zivpn-manager add"
            echo "  Username (3-32 karakter): john_doe"
            echo "  Password [Enter = auto: aB3kX9mP2q]: "
            echo "  Durasi (hari) [Enter = 30]: 60"
            echo ""
            echo -e "${BOLD}Catatan:${RESET}"
            echo "  - Username harus unik, tidak boleh sama dengan akun lain"
            echo "  - Password yang sama antar akun sebaiknya dihindari"
            echo "  - Service akan otomatis di-restart setelah akun ditambahkan"
            echo ""
            ;;

        delete)
            echo ""
            echo -e "${BOLD}zivpn-manager delete${RESET}"
            echo ""
            echo -e "${BOLD}Deskripsi:${RESET}"
            echo "  Menghapus akun VPN secara permanen. Akun yang dihapus tidak"
            echo "  bisa dikembalikan (kecuali Anda punya backup)."
            echo ""
            echo -e "${BOLD}Penggunaan:${RESET}"
            echo "  zivpn-manager delete"
            echo ""
            echo -e "${BOLD}Langkah-langkah:${RESET}"
            echo "  1. Daftar akun akan ditampilkan"
            echo "  2. Masukkan username yang ingin dihapus"
            echo "  3. Konfirmasi penghapusan"
            echo ""
            echo -e "${BOLD}Contoh:${RESET}"
            echo "  \$ zivpn-manager delete"
            echo "  Username yang akan dihapus: john_doe"
            echo "  Hapus akun 'john_doe'? (y/n): y"
            echo ""
            echo -e "${BOLD}Tips:${RESET}"
            echo "  Buat backup terlebih dahulu sebelum menghapus akun:"
            echo "  \$ zivpn-manager backup"
            echo ""
            ;;

        trial)
            echo ""
            echo -e "${BOLD}zivpn-manager trial${RESET}"
            echo ""
            echo -e "${BOLD}Deskripsi:${RESET}"
            echo "  Membuat akun percobaan (trial) dengan durasi pendek."
            echo "  Password akan di-generate otomatis. Akun trial ditandai"
            echo "  khusus di daftar akun agar mudah dibedakan."
            echo ""
            echo -e "${BOLD}Penggunaan:${RESET}"
            echo "  zivpn-manager trial"
            echo ""
            echo -e "${BOLD}Langkah-langkah:${RESET}"
            echo "  1. Masukkan username untuk akun trial"
            echo "  2. Masukkan durasi dalam hari (default: 1 hari)"
            echo "  3. Konfirmasi pembuatan"
            echo ""
            echo -e "${BOLD}Contoh:${RESET}"
            echo "  \$ zivpn-manager trial"
            echo "  Username untuk trial: coba_user"
            echo "  Durasi trial (hari) [Enter = 1]: 3"
            echo ""
            ;;

        extend)
            echo ""
            echo -e "${BOLD}zivpn-manager extend${RESET}"
            echo ""
            echo -e "${BOLD}Deskripsi:${RESET}"
            echo "  Memperpanjang masa aktif akun yang sudah ada. Jika akun masih"
            echo "  aktif, hari ditambahkan dari tanggal expired saat ini. Jika akun"
            echo "  sudah expired, hari dihitung dari sekarang dan status kembali aktif."
            echo ""
            echo -e "${BOLD}Penggunaan:${RESET}"
            echo "  zivpn-manager extend"
            echo ""
            echo -e "${BOLD}Langkah-langkah:${RESET}"
            echo "  1. Daftar akun akan ditampilkan"
            echo "  2. Masukkan username yang ingin diperpanjang"
            echo "  3. Masukkan jumlah hari tambahan (default: 30 hari)"
            echo ""
            echo -e "${BOLD}Contoh:${RESET}"
            echo "  \$ zivpn-manager extend"
            echo "  Username: john_doe"
            echo "  Tambah berapa hari [Enter = 30]: 30"
            echo ""
            echo -e "${BOLD}Cara kerja perpanjangan:${RESET}"
            echo "  - Akun aktif, expired 20 Mar + 30 hari = expired 19 Apr"
            echo "  - Akun expired + 30 hari = expired 30 hari dari sekarang"
            echo ""
            ;;

        set-expired)
            echo ""
            echo -e "${BOLD}zivpn-manager set-expired${RESET}"
            echo ""
            echo -e "${BOLD}Deskripsi:${RESET}"
            echo "  Mengatur tanggal expired akun ke tanggal tertentu."
            echo "  Berguna untuk menyesuaikan masa aktif secara manual."
            echo ""
            echo -e "${BOLD}Penggunaan:${RESET}"
            echo "  zivpn-manager set-expired"
            echo ""
            echo -e "${BOLD}Langkah-langkah:${RESET}"
            echo "  1. Daftar akun akan ditampilkan"
            echo "  2. Masukkan username"
            echo "  3. Masukkan tanggal expired baru (format: YYYY-MM-DD)"
            echo ""
            echo -e "${BOLD}Contoh:${RESET}"
            echo "  \$ zivpn-manager set-expired"
            echo "  Username: john_doe"
            echo "  Tanggal expired baru (YYYY-MM-DD): 2026-06-30"
            echo ""
            ;;

        backup)
            echo ""
            echo -e "${BOLD}zivpn-manager backup${RESET}"
            echo ""
            echo -e "${BOLD}Deskripsi:${RESET}"
            echo "  Membuat file backup berisi semua data penting ZiVPN."
            echo "  File backup disimpan di /etc/zivpn/backups/ dalam format .tar.gz"
            echo "  dengan nama berisi timestamp (contoh: zivpn-backup_20260308_193000.tar.gz)."
            echo ""
            echo -e "${BOLD}File yang di-backup:${RESET}"
            echo "  - /etc/zivpn/accounts.json    Database akun pengguna"
            echo "  - /etc/zivpn/config.json       Konfigurasi service ZiVPN"
            echo "  - /etc/zivpn/manager.conf      Konfigurasi manager (custom domain dll)"
            echo "  - /etc/zivpn/zivpn.crt         Sertifikat SSL"
            echo "  - /etc/zivpn/zivpn.key          Private key SSL"
            echo ""
            echo -e "${BOLD}Penggunaan:${RESET}"
            echo "  zivpn-manager backup"
            echo ""
            echo -e "${BOLD}Contoh:${RESET}"
            echo "  \$ zivpn-manager backup"
            echo "  [✓] Backup berhasil dibuat!"
            echo "  File : /etc/zivpn/backups/zivpn-backup_20260308_193000.tar.gz"
            echo ""
            echo -e "${BOLD}Migrasi ke server baru:${RESET}"
            echo "  1. Buat backup di server lama:"
            echo "     \$ zivpn-manager backup"
            echo ""
            echo "  2. Salin file backup ke server baru:"
            echo "     \$ scp /etc/zivpn/backups/zivpn-backup_*.tar.gz root@IP_BARU:/tmp/"
            echo ""
            echo "  3. Di server baru, install ZiVPN terlebih dahulu, lalu restore:"
            echo "     \$ zivpn-manager restore"
            echo "     Pilih file dari /tmp/ atau pindahkan ke /etc/zivpn/backups/"
            echo ""
            ;;

        restore)
            echo ""
            echo -e "${BOLD}zivpn-manager restore${RESET}"
            echo ""
            echo -e "${BOLD}Deskripsi:${RESET}"
            echo "  Mengembalikan data ZiVPN dari file backup (.tar.gz)."
            echo "  Anda bisa memilih dari daftar backup yang tersedia di"
            echo "  /etc/zivpn/backups/ atau memasukkan path file secara manual."
            echo ""
            echo -e "${BOLD}Penggunaan:${RESET}"
            echo "  zivpn-manager restore"
            echo ""
            echo -e "${BOLD}Langkah-langkah:${RESET}"
            echo "  1. Pilih file backup dari daftar atau masukkan path manual"
            echo "  2. Preview isi backup dan jumlah akun ditampilkan"
            echo "  3. Konfirmasi restore"
            echo "  4. Data saat ini di-backup otomatis (safety backup)"
            echo "  5. Data dari backup di-restore dan service di-restart"
            echo ""
            echo -e "${BOLD}Contoh:${RESET}"
            echo "  \$ zivpn-manager restore"
            echo "  Backup tersedia:"
            echo "  [1] zivpn-backup_20260308_193000.tar.gz  (4.0K, 2026-03-08 19:30:00)"
            echo "  [p] Masukkan path file backup manual"
            echo "  [0] Batal"
            echo "  Pilih backup [0-1/p]: 1"
            echo ""
            echo -e "${BOLD}Keamanan:${RESET}"
            echo "  - Sebelum restore, data saat ini otomatis di-backup terlebih dahulu"
            echo "    sebagai safety net (disimpan dengan nama zivpn-pre-restore_*.tar.gz)"
            echo "  - File backup yang sudah di-restore akan diverifikasi"
            echo ""
            ;;

        backups)
            echo ""
            echo -e "${BOLD}zivpn-manager backups${RESET}"
            echo ""
            echo -e "${BOLD}Deskripsi:${RESET}"
            echo "  Menampilkan daftar semua file backup yang tersedia"
            echo "  di direktori /etc/zivpn/backups/."
            echo ""
            echo -e "${BOLD}Penggunaan:${RESET}"
            echo "  zivpn-manager backups"
            echo ""
            echo -e "${BOLD}Contoh output:${RESET}"
            echo "  No   Nama File                                    Size     Tanggal"
            echo "  1    zivpn-backup_20260308_193000.tar.gz           4.0K     2026-03-08 19:30:00"
            echo "  2    zivpn-pre-restore_20260309_100000.tar.gz      4.0K     2026-03-09 10:00:00"
            echo ""
            ;;

        status)
            echo ""
            echo -e "${BOLD}zivpn-manager status${RESET}"
            echo ""
            echo -e "${BOLD}Deskripsi:${RESET}"
            echo "  Menampilkan status service ZiVPN (running/stopped) beserta"
            echo "  informasi detail dari systemd."
            echo ""
            echo -e "${BOLD}Penggunaan:${RESET}"
            echo "  zivpn-manager status"
            echo ""
            ;;

        restart)
            echo ""
            echo -e "${BOLD}zivpn-manager restart${RESET}"
            echo ""
            echo -e "${BOLD}Deskripsi:${RESET}"
            echo "  Restart service ZiVPN. Berguna setelah melakukan perubahan"
            echo "  konfigurasi manual atau jika service bermasalah."
            echo ""
            echo -e "${BOLD}Penggunaan:${RESET}"
            echo "  zivpn-manager restart"
            echo ""
            echo -e "${BOLD}Catatan:${RESET}"
            echo "  Service otomatis di-restart saat menambah, menghapus, atau"
            echo "  mengubah akun. Perintah ini hanya perlu dijalankan manual"
            echo "  jika ada masalah."
            echo ""
            ;;

        info)
            echo ""
            echo -e "${BOLD}zivpn-manager info${RESET}"
            echo ""
            echo -e "${BOLD}Deskripsi:${RESET}"
            echo "  Menampilkan informasi server dan konfigurasi ZiVPN termasuk:"
            echo "  IP publik, custom domain, port, obfuscation, lokasi file config,"
            echo "  dan status service."
            echo ""
            echo -e "${BOLD}Penggunaan:${RESET}"
            echo "  zivpn-manager info"
            echo ""
            ;;

        expire-check)
            echo ""
            echo -e "${BOLD}zivpn-manager expire-check${RESET}"
            echo ""
            echo -e "${BOLD}Deskripsi:${RESET}"
            echo "  Memeriksa semua akun aktif dan menonaktifkan akun yang sudah"
            echo "  melewati tanggal expired. Perintah ini dijalankan otomatis"
            echo "  setiap jam melalui cron job."
            echo ""
            echo -e "${BOLD}Penggunaan:${RESET}"
            echo "  zivpn-manager expire-check"
            echo ""
            echo -e "${BOLD}Catatan:${RESET}"
            echo "  Anda biasanya tidak perlu menjalankan perintah ini manual."
            echo "  Cron job sudah dikonfigurasi saat instalasi di:"
            echo "  /etc/cron.d/zivpn-manager"
            echo ""
            ;;

        update)
            echo ""
            echo -e "${BOLD}zivpn-manager update${RESET}"
            echo ""
            echo -e "${BOLD}Deskripsi:${RESET}"
            echo "  Mengecek apakah ada versi terbaru ZiVPN Manager di GitHub."
            echo "  Jika ada update, Anda bisa memilih untuk menginstall versi"
            echo "  terbaru atau tetap menggunakan versi saat ini."
            echo ""
            echo -e "${BOLD}Penggunaan:${RESET}"
            echo "  zivpn-manager update"
            echo ""
            echo -e "${BOLD}Contoh:${RESET}"
            echo "  \$ zivpn-manager update"
            echo "  Versi terpasang : v1.3.0"
            echo "  Versi terbaru   : v1.4.0"
            echo ""
            echo "  ⬆  Update tersedia: v1.3.0 → v1.4.0"
            echo ""
            echo "  [1] Update ke v1.4.0"
            echo "  [2] Gunakan versi sekarang (skip)"
            echo "  Pilih [1/2]: 1"
            echo ""
            echo -e "${BOLD}Cara kerja:${RESET}"
            echo "  1. Membandingkan versi lokal dengan versi di GitHub"
            echo "  2. Jika ada update, menampilkan pilihan update atau skip"
            echo "  3. Jika memilih update:"
            echo "     - Mengunduh semua file terbaru dari GitHub"
            echo "     - Membuat backup versi lama secara otomatis"
            echo "     - Mengganti file dengan versi baru"
            echo "  4. Jalankan 'zivpn-manager' kembali untuk menggunakan versi baru"
            echo ""
            echo -e "${BOLD}Catatan:${RESET}"
            echo "  - Membutuhkan koneksi internet ke github.com"
            echo "  - Data akun (accounts.json) tidak terpengaruh oleh update"
            echo "  - Backup otomatis dibuat sebelum update di /etc/zivpn/backups/"
            echo ""
            ;;

        uninstall)
            echo ""
            echo -e "${BOLD}zivpn-manager uninstall${RESET}"
            echo ""
            echo -e "${BOLD}Deskripsi:${RESET}"
            echo "  Menghapus ZiVPN dan ZiVPN Manager secara menyeluruh dari server."
            echo "  Termasuk service, binary, konfigurasi, database akun, sertifikat,"
            echo "  cron job, dan aturan firewall."
            echo ""
            echo -e "${BOLD}Penggunaan:${RESET}"
            echo "  zivpn-manager uninstall"
            echo ""
            echo -e "${BOLD}Langkah-langkah:${RESET}"
            echo "  1. Tampilan peringatan dan daftar yang akan dihapus"
            echo "  2. Pilih tindakan:"
            echo "     [1] Backup dulu, lalu uninstall — data di-backup sebelum hapus"
            echo "     [2] Langsung uninstall — tanpa backup (hati-hati!)"
            echo "     [3] Batal"
            echo "  3. Jika memilih backup, file backup disalin ke /root/ secara otomatis"
            echo "  4. Konfirmasi terakhir sebelum eksekusi"
            echo ""
            echo -e "${BOLD}Contoh:${RESET}"
            echo "  \$ zivpn-manager uninstall"
            echo "  Pilih tindakan:"
            echo "  [1] Backup dulu, lalu uninstall"
            echo "  [2] Langsung uninstall (tanpa backup)"
            echo "  [3] Batal"
            echo "  Pilih [1/2/3]: 1"
            echo ""
            echo -e "${BOLD}Catatan:${RESET}"
            echo "  - Jika memilih backup, file disimpan di /root/ agar tidak ikut terhapus"
            echo "  - File backup bisa digunakan untuk restore di server baru"
            echo "  - Proses ini tidak bisa dibatalkan setelah konfirmasi terakhir"
            echo ""
            ;;

        domain)
            echo ""
            echo -e "${BOLD}zivpn-manager domain${RESET}"
            echo ""
            echo -e "${BOLD}Deskripsi:${RESET}"
            echo "  Mengatur custom domain untuk server ZiVPN. Domain ini"
            echo "  ditampilkan di header manager dan info akun yang diberikan"
            echo "  ke pengguna. Jika tidak diset, IP publik yang digunakan."
            echo ""
            echo -e "${BOLD}Penggunaan:${RESET}"
            echo "  zivpn-manager domain"
            echo ""
            echo -e "${BOLD}Langkah-langkah:${RESET}"
            echo "  1. Domain saat ini ditampilkan (jika ada)"
            echo "  2. Masukkan domain baru, atau kosongkan untuk menghapus"
            echo "  3. Konfirmasi perubahan"
            echo ""
            echo -e "${BOLD}Contoh:${RESET}"
            echo "  \$ zivpn-manager domain"
            echo "  Domain saat ini : (belum diset)"
            echo "  Domain baru: vpn.namadomain.com"
            echo "  [✓] Custom domain disimpan: vpn.namadomain.com"
            echo ""
            echo -e "${BOLD}Catatan:${RESET}"
            echo "  Pastikan domain sudah di-pointing (A record) ke IP server ini"
            echo "  sebelum mengaturnya di sini."
            echo ""
            ;;

        *)
            echo ""
            echo -e "${RED}[✗]${RESET} Perintah '${topic}' tidak dikenali."
            echo ""
            echo "Perintah yang tersedia:"
            echo "  list, add, delete, trial, extend, set-expired, domain,"
            echo "  backup, restore, backups, status, restart, info,"
            echo "  update, uninstall, expire-check"
            echo ""
            echo "Contoh: zivpn-manager help backup"
            echo ""
            ;;
    esac
}

# ---------------------------------------------------------------------------
# show_help — Main help handler (dispatch)
# ---------------------------------------------------------------------------
show_help() {
    local topic="${1:-}"
    if [[ -z "$topic" ]]; then
        show_usage
    else
        show_help_topic "$topic"
    fi
}
